modLoader="javafml"
loaderVersion="[36,)"
license="Apache 2.0 License"
issueTrackerURL="https://github.com/ChipmunkCraft/ChipDevTools/issues"
[[mods]]
modId="chipdevtools"
version="${file.jarVersion}"
displayName="ChipDevTools"
# A URL to query for updates for this mod. See the JSON update specification https://mcforge.readthedocs.io/en/latest/gettingstarted/autoupdate/
#updateJSONURL="https://change.me.example.invalid/updates.json"
# A URL for the "homepage" for this mod, displayed in the mod UI
displayURL="https://github.com/ChipmunkCraft/ChipDevTools"
authors="Chipmunk"
# The description text for the mod (multi line!)
description='''
Chipmunks Dev Tools provides some tools to aid in the development of mods and modpacks.  This mod and associated files should be removed before publishing a mod/modpack
'''
[[dependencies.chipdevtools]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
# Here's another dependency
[[dependencies.chipdevtools]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
