modLoader="javafml"
loaderVersion="${loader_version}"
license="${mod_license}"
issueTrackerURL="${mod_issue_tracker_url}"
[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="${mod_display_url}"
# A file name (in the root of the mod JAR) containing a logo for display
#logoFile="examplemod.png"
authors="${mod_authors}"
description='''${mod_description}'''
[[dependencies.chipsdevtools]]
    modId="neoforge"
    type="required"
    ordering="NONE"
    side="BOTH"
# Here's another dependency
[[dependencies.chipsdevtools]]
    modId="minecraft"
    type="required"
    ordering="NONE"
    side="BOTH"
# Here's another dependency
[[dependencies.chipsdevtools]]
    modId="chipsdevtools"
    type="required"
    ordering="NONE"
    side="CLIENT"
